services:
  kinesis_stream_producer:
    image: $IMAGE_NAME
    environment:
      IP_CAM: $IP_CAM
      USERNAME_CAM: $USERNAME_CAM
      PASSWORD_CAM: $PASSWORD_CAM
      STREAM_NAME: $STREAM_NAME
      REGION: $REGION
      ACCESS_KEY_ID: $ACCESS_KEY_ID
      SECRET_KEY: $SECRET_KEY
      GST_PLUGIN_PATH: /opt/app/amazon-kinesis-video-streams-producer-sdk-cpp/build
      no_proxy: $IP_CAM
    command: /bin/sh "start_stream.sh"
