name: Build and Push Kinesis Video Stream Application Image
on:
  push:
    tags:
      - "*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm32v7", "arm64v8"]
        include:
          - tag_ext: "armv7hf"
            arch: "arm32v7"
          - tag_ext: "aarch64"
            arch: "arm64v8"
    env:
      IMAGE_NAME: kinesis-video-stream-application

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Use Qemu
        uses: docker/setup-qemu-action@v2

      - name: Use Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the image
        run: |
          docker run --privileged --rm multiarch/qemu-user-static
          docker build -t axisecp/$IMAGE_NAME:latest-${{ matrix.tag_ext }} . --build-arg ARCH=${{ matrix.arch }}

      - name: Push the image to DockerHub
        run: docker push axisecp/$IMAGE_NAME:latest-${{ matrix.tag_ext }}
