name: Build Kinesis Video Streams producer image
on:
  push:
    branches:
      - "dev"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm32v7", "arm64v8"]
    env:
      IMAGE_NAME: kinesis-vsp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Use Qemu
        uses: docker/setup-qemu-action@v2

      - name: Use Docker buildx
        uses: docker/setup-buildx-action@v2

#      - name: Docker login
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the image
        run: |
          docker run --privileged --rm multiarch/qemu-user-static
          docker build -t $IMAGE_NAME . --build-arg ARCH=${{ matrix.arch }}
