name: Build and Push Kinesis Video Stream Application Image

on:
  push:
    tags:
      - "*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm32v7", "arm64v8"]
        include:
          - tag_ext: "armv7hf"
            arch: "arm32v7"
          - tag_ext: "aarch64"
            arch: "arm64v8"
    env:
      IMAGE_NAME: kinesis-video-stream-application

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Qemu
        uses: docker/setup-qemu-action@v2

      - name: Use Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args:
            ARCH: ${{ matrix.arch }}
          tags: axisecp/${{ env.IMAGE_NAME }}:latest-${{ matrix.tag_ext }}
          push: true
