name: Build and Push Kinesis Video Stream Application Image

on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm32v7", "arm64v8"]
        include:
          - tag_ext: "armv7hf"
            arch: "arm32v7"
          - tag_ext: "aarch64"
            arch: "arm64v8"
    env:
      IMAGE_NAME: ${{ github.repository }}
      REGISTRY: ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Qemu
        uses: docker/setup-qemu-action@v2

      - name: Use Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Print metadata values
        run: |
          echo ${{ steps.metadata.output.tags }}
          echo ${{ steps.metadata.output.labels }}

#      - name: Build and push image to GitHub Container Registry
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          build-args: ARCH=${{ matrix.arch }}
#          tags: ${{ steps.metadata.output.tags }}
#          labels: ${{ steps.metadata.output.labels }}
#          push: true
