---
name: Continuous integration workflow

on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Run Super-Linter
        uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7 # v4.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: /
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
