name: Run markdown lint on README.md

on:
  push:
    branches:
      - "dev"

jobs:
  markdown_lint:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
      - name: README.md lint
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
